CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME        VARCHAR2(100),
    AGE         NUMBER,
    BALANCE     NUMBER(12, 2),
    IS_VIP      CHAR(1) DEFAULT 'N'
);

CREATE TABLE LOANS (
    LOAN_ID       NUMBER PRIMARY KEY,
    CUSTOMER_ID   NUMBER
        REFERENCES CUSTOMERS ( CUSTOMER_ID ),
    INTEREST_RATE NUMBER(5, 2),
    DUE_DATE      DATE
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID   NUMBER PRIMARY KEY,
    CUSTOMER_ID  NUMBER
        REFERENCES CUSTOMERS ( CUSTOMER_ID ),
    ACCOUNT_TYPE VARCHAR2(20),
    BALANCE      NUMBER(12, 2)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID   NUMBER PRIMARY KEY,
    NAME          VARCHAR2(100),
    DEPARTMENT_ID NUMBER,
    SALARY        NUMBER(10, 2)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID   NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100)
);